# Generated by Django 4.2.4 on 2023-08-29 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_accountuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountuser',
            name='username',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
