# Generated by Django 4.2.4 on 2023-08-29 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_accountuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountuser',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
