# Generated by Django 4.2.4 on 2023-09-01 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_accountuser_is_superuser'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='accountuser',
            managers=[
            ],
        ),
    ]
