# Generated by Django 4.2.4 on 2023-09-01 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menuitem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('price', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Price')),
                ('category', models.CharField(max_length=40, verbose_name='category')),
                ('itemtype', models.BooleanField(verbose_name=False)),
                ('img', models.ImageField(upload_to='')),
                ('available', models.BooleanField(verbose_name=False)),
                ('calorie', models.ImageField(upload_to='')),
            ],
        ),
    ]
