# Generated by Django 4.2.4 on 2023-09-01 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='calorie',
            field=models.IntegerField(),
        ),
    ]
