# Generated by Django 4.2.4 on 2023-09-03 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_remove_menuitem_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='img',
            field=models.ImageField(null=True, upload_to='menu-images/'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='price',
            field=models.DecimalField(decimal_places=1, max_digits=6, verbose_name='Price'),
        ),
    ]
