# Generated by Django 4.2.4 on 2023-09-13 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_alter_menuitem_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='calorie',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='itemtype',
            field=models.BooleanField(blank=True, verbose_name=False),
        ),
    ]
