# Generated by Django 4.2.4 on 2023-09-15 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_alter_menuitem_itemtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='itemtype',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
