# Generated by Django 4.2.4 on 2023-09-15 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_alter_menuitem_itemtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='itemtype',
            field=models.CharField(choices=[('VEG', 'Vegetarian'), ('NON_VEG', 'Non-Vegetarian'), ('NONE', 'None of them')], default='NONE', max_length=8),
        ),
    ]
