# Generated by Django 4.2.4 on 2023-09-06 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0002_order_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_id', models.IntegerField()),
                ('f_id', models.IntegerField()),
                ('quantity', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.FloatField(),
        ),
    ]
