# Generated by Django 4.2.4 on 2023-09-07 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0004_alter_cart_options_alter_cart_f_id_alter_cart_u_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='totalPrice',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
